import type {
  Site,
  Block,
  Apartment,
  Owner,
  Tenant,
  UserRecord,
  Due,
  Payment,
  Expense,
  Announcement,
  Ticket,
  PropertyDocument,
  AuditLog,
  DashboardData,
} from './types'

export const INITIAL_USERS: UserRecord[] = [
  {
    id: 'user-admin-01',
    email: 'admin@site.com',
    fullName: 'Yönetici Admin',
    phone: '05551112233',
    role: 'ADMIN',
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'user-manager-01',
    email: 'manager@site.com',
    fullName: 'Site Müdürü Kemal',
    phone: '05552223344',
    role: 'MANAGER',
    isActive: true,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'user-resident-01',
    email: 'ahmet@site.com',
    fullName: 'Ahmet Yılmaz',
    phone: '05321112233',
    role: 'RESIDENT',
    isActive: true,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'user-resident-02',
    email: 'ayse@site.com',
    fullName: 'Ayşe Demir',
    phone: '05332223344',
    role: 'RESIDENT',
    isActive: true,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
]

export const INITIAL_SITES: Site[] = [
  {
    id: 'site-01',
    name: 'Güneş Park Evleri',
    address: 'Atatürk Mah. Karanfil Sok. No: 12, Çankaya / Ankara',
    phone: '0312 444 0 123',
    email: 'yonetim@gunespark.com',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'site-02',
    name: 'Mavişehir Konakları',
    address: 'Mavişehir Mah. Sahil Bulvarı No: 45, Karşıyaka / İzmir',
    phone: '0232 333 44 55',
    email: 'bilgi@mavisehir.com',
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
]

export const INITIAL_BLOCKS: Block[] = [
  {
    id: 'block-01',
    siteId: 'site-01',
    name: 'A Blok',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-02',
    siteId: 'site-01',
    name: 'B Blok',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-03',
    siteId: 'site-02',
    name: 'Manzara Blok',
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const INITIAL_APARTMENTS: Apartment[] = [
  {
    id: 'apt-01',
    blockId: 'block-01',
    ownerId: 'user-resident-01',
    residentId: 'user-resident-01',
    apartmentNumber: 'D:1',
    floor: 1,
    apartmentType: '3+1',
    tapuNumber: 'TP-109283',
    isActive: true,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'apt-02',
    blockId: 'block-01',
    ownerId: 'user-resident-02',
    residentId: null,
    apartmentNumber: 'D:2',
    floor: 1,
    apartmentType: '2+1',
    tapuNumber: 'TP-109284',
    isActive: true,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'apt-03',
    blockId: 'block-02',
    ownerId: 'user-resident-02',
    residentId: null,
    apartmentNumber: 'D:5',
    floor: 3,
    apartmentType: '4+1',
    tapuNumber: 'TP-209112',
    isActive: true,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'apt-04',
    blockId: 'block-03',
    ownerId: null,
    residentId: null,
    apartmentNumber: 'D:12',
    floor: 6,
    apartmentType: '3+1 Dubleks',
    tapuNumber: 'TP-301145',
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const INITIAL_OWNERS: Owner[] = [
  {
    id: 'owner-01',
    apartmentId: 'apt-01',
    fullName: 'Ahmet Yılmaz',
    phone: '05321112233',
    email: 'ahmet@site.com',
    idNumber: '12345678901',
    isActive: true,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'owner-02',
    apartmentId: 'apt-02',
    fullName: 'Ayşe Demir',
    phone: '05332223344',
    email: 'ayse@site.com',
    idNumber: '98765432109',
    isActive: true,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'owner-03',
    apartmentId: 'apt-03',
    fullName: 'Mehmet Kaya',
    phone: '05445556677',
    email: 'mehmet.kaya@email.com',
    idNumber: '55443322110',
    isActive: true,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-01',
    apartmentId: 'apt-02',
    fullName: 'Canberk Özkan',
    phone: '05051234567',
    email: 'canberk@gmail.com',
    idNumber: '22334455667',
    moveInDate: '2025-01-15T00:00:00.000Z',
    moveOutDate: null,
    monthlyRent: 24000,
    monthlyDue: 2500,
    defaultBillSupport: 2500,
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tenant-02',
    apartmentId: 'apt-03',
    fullName: 'Zeynep Yıldız',
    phone: '05067890123',
    email: 'zeynep.yildiz@gmail.com',
    idNumber: '88776655443',
    moveInDate: '2024-06-01T00:00:00.000Z',
    moveOutDate: null,
    monthlyRent: 30000,
    monthlyDue: 3200,
    defaultBillSupport: 1500,
    isActive: true,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const INITIAL_DUES: Due[] = [
  {
    id: 'due-01',
    apartmentId: 'apt-01',
    tenantId: null,
    dueType: 'AIDAT',
    amount: 2500,
    period: '2026-08',
    dueDate: '2026-08-15T00:00:00.000Z',
    status: 'PAID',
    electricityAmount: 0,
    waterAmount: 0,
    gasAmount: 0,
    billSupportAmount: 0,
    grossAmount: 2500,
    description: 'Ağustos Ayı Genel Aidat',
    totalPaid: 2500,
    remainingAmount: 0,
    isOverdue: false,
    daysOverdue: 0,
  },
  {
    id: 'due-02',
    apartmentId: 'apt-02',
    tenantId: 'tenant-01',
    dueType: 'AIDAT',
    amount: 2500,
    period: '2026-08',
    dueDate: '2026-08-15T00:00:00.000Z',
    status: 'PAID',
    electricityAmount: 0,
    waterAmount: 0,
    gasAmount: 0,
    billSupportAmount: 0,
    grossAmount: 2500,
    description: 'Ağustos Ayı Aidat Bedeli',
    totalPaid: 2500,
    remainingAmount: 0,
    isOverdue: false,
    daysOverdue: 0,
  },
  {
    id: 'due-03',
    apartmentId: 'apt-03',
    tenantId: 'tenant-02',
    dueType: 'AIDAT',
    amount: 3200,
    period: '2026-08',
    dueDate: '2026-08-10T00:00:00.000Z',
    status: 'PENDING',
    electricityAmount: 0,
    waterAmount: 0,
    gasAmount: 0,
    billSupportAmount: 0,
    grossAmount: 3200,
    description: 'Ağustos Ayı Aidat Bedeli',
    totalPaid: 1000,
    remainingAmount: 2200,
    isOverdue: true,
    daysOverdue: 15,
  },
  {
    id: 'due-04',
    apartmentId: 'apt-02',
    tenantId: 'tenant-01',
    dueType: 'KIRA',
    amount: 24000,
    period: '2026-08',
    dueDate: '2026-08-05T00:00:00.000Z',
    status: 'PAID',
    electricityAmount: 0,
    waterAmount: 0,
    gasAmount: 0,
    billSupportAmount: 0,
    grossAmount: 24000,
    description: 'Ağustos Kira Bedeli',
    totalPaid: 24000,
    remainingAmount: 0,
    isOverdue: false,
    daysOverdue: 0,
  },
]

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'payment-01',
    dueId: 'due-01',
    amountPaid: 2500,
    paymentDate: '2026-08-12T14:30:00.000Z',
    paymentMethod: 'Kredi Kartı (Online)',
  },
  {
    id: 'payment-02',
    dueId: 'due-02',
    amountPaid: 2500,
    paymentDate: '2026-08-14T11:00:00.000Z',
    paymentMethod: 'Havale / EFT',
  },
  {
    id: 'payment-03',
    dueId: 'due-03',
    amountPaid: 1000,
    paymentDate: '2026-08-18T16:20:00.000Z',
    paymentMethod: 'Havale / EFT',
  },
  {
    id: 'payment-04',
    dueId: 'due-04',
    amountPaid: 24000,
    paymentDate: '2026-08-04T10:15:00.000Z',
    paymentMethod: 'Banka Havalesi',
  },
]

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'expense-01',
    title: 'A ve B Blok Asansör Periyodik Bakım',
    amount: 8500,
    category: 'Bakım & Onarım',
    expenseDate: '2026-08-08T09:00:00.000Z',
    invoiceUrl: 'FAT-2026-ASAN-01',
  },
  {
    id: 'expense-02',
    title: 'Site Ortak Alan Aydınlatma Elektrik Faturası',
    amount: 14200,
    category: 'Elektrik & Su Ortak Alan',
    expenseDate: '2026-08-11T10:00:00.000Z',
    invoiceUrl: 'ENR-2026-08819',
  },
  {
    id: 'expense-03',
    title: 'Ortak Alan Temizlik Malzemeleri Alımı',
    amount: 3400,
    category: 'Temizlik',
    expenseDate: '2026-08-15T15:00:00.000Z',
    invoiceUrl: 'TMZ-99120',
  },
]

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: 'Aylık Olağan Kat Malikleri Toplantısı',
    content: 'Değerli site sakinlerimiz, 30 Ağustos Pazar günü saat 14:00’te Site Sosyal Tesisinde genel kurul toplantımız yapılacaktır. Katılımınızı rica ederiz.',
    createdBy: 'user-admin-01',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'ann-02',
    title: 'Su Kesintisi ve Hidrofor Bakımı Hakkında',
    content: '28 Ağustos Cuma günü 13:00 - 16:00 saatleri arasında hidrofor ana vanalarında yapılacak bakım nedeniyle kısa süreli su kesintisi yaşanabilir.',
    createdBy: 'user-manager-01',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
]

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'ticket-01',
    userId: 'user-resident-01',
    title: 'A Blok 1. Kat Koridor Lambası Yanmıyor',
    description: 'Koridordaki sensörlü lamba arızalandı, akşamları karanlık oluyor.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'ticket-02',
    userId: 'user-resident-02',
    title: 'Otopark Giriş Kumandası Tanımlama',
    description: 'Yeni aldığım araç için otopark bariyerine plaka tanımlaması yapılmasını rica ediyorum.',
    status: 'OPEN',
    priority: 'LOW',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
]

export const INITIAL_DOCUMENTS: PropertyDocument[] = [
  {
    id: 'doc-01',
    entityType: 'APARTMENT',
    entityId: 'apt-01',
    documentCategory: 'Tapu',
    fileName: 'tapu_d1.pdf',
    fileUrl: 'https://example.com/docs/tapu_d1.pdf',
    notes: 'Resmi kat mülkiyeti tapu fotokopisi',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'doc-02',
    entityType: 'TENANT',
    entityId: 'tenant-01',
    documentCategory: 'Kira Sözleşmesi',
    fileName: 'kira_sozlesmesi_canberk.pdf',
    fileUrl: 'https://example.com/docs/sozlesme.pdf',
    notes: '1 Yıllık noter onaylı kira kontratı',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
]

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-01',
    userId: 'user-admin-01',
    action: 'CREATE',
    entityName: 'Due',
    entityId: 'due-01',
    timestamp: new Date(Date.now() - 10 * 86400000).toISOString(),
    details: 'Ağustos 2026 dönemi aidat tahakkuku oluşturuldu.',
  },
  {
    id: 'audit-02',
    userId: 'user-admin-01',
    action: 'PAYMENT',
    entityName: 'Payment',
    entityId: 'payment-01',
    timestamp: new Date(Date.now() - 8 * 86400000).toISOString(),
    details: '2.500 ₺ tutarında aidat ödemesi tahsil edildi.',
  },
]

export function getInitialDashboardData(): DashboardData {
  return {
    sites: INITIAL_SITES,
    blocks: INITIAL_BLOCKS,
    apartments: INITIAL_APARTMENTS,
    owners: INITIAL_OWNERS,
    tenants: INITIAL_TENANTS,
    dues: INITIAL_DUES,
    payments: INITIAL_PAYMENTS,
    expenses: INITIAL_EXPENSES,
    announcements: INITIAL_ANNOUNCEMENTS,
    tickets: INITIAL_TICKETS,
    auditLogs: INITIAL_AUDIT_LOGS,
    users: INITIAL_USERS,
  }
}
